name: Trigger External Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repo
        env:
          GH_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/leshy/leshy.github.io/dispatches \
            -d '{"event_type":"rebuild_web"}'
